activeBPM/urls.py
__author__ = 'torn'

from django.conf.urls import patterns, include, url
from activeBPM import views
from django.views.generic.base import TemplateView

#TODO 404 page
moldslist_patterns = patterns('',
    url(r'^zip-folder$', views.zip_folder_task_file, name='zip-folder-task-file'),

    url(r'^process-status$', views.proc_status_view, name='process-status'),
    url(r'^process-init$', views.proc_init_view, name='process-init'),
    url(r'^process-task$', views.task_view, name='process-task'),
    url(r'^all-processes$', views.all_proc_view, name='all-processes'),
    url(r'^process-control$', views.proc_control_view, name='process-control'),
    url(r'^task-control$', views.task_control, name='task-control'),
    url(r'^file-control$', views.file_control, name='file-control'),
    url(r'^var-control$', views.var_control, name='variable-control'),
    url(r'^process-xml$', views.proc_xml, name='process-xml'),
    url(r'^doc-view$', TemplateView.as_view(template_name='activeBPM/doc_view.html'),
        name='documentation-view'),
    url(r'^$', views.proc_dashboard_view, name='process-dashboard'),
)

urlpatterns = patterns('',
    url(r'^', include(moldslist_patterns, namespace='activeBPM')),
)

devhim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.decorators import login_required

handler404 = 'site_utils.handler404'
handler500 = 'site_utils.handler500'

admin.site.site_header = 'УкрХимПласт - Разработка форм'
admin.site_title = 'УкрХимПласт - Разработка форм'
admin.index_title = 'УкрХимПласт - Разработка форм'

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)

urlpatterns = patterns('', url(r'^admin/', include(admin.site.urls)))


if hasattr(settings, 'ENABLE_SILK') and settings.ENABLE_SILK:
    urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('', url(r'^', include('activeBPM.urls'), name='dev-home'))

activeBPM/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import ntpath
import os
from django.conf import settings

#TODO Add a long descriptions, account existence test (all other things is available through BPMS admin)
class BPMSUser(models.Model):
    login = models.CharField(max_length=50,  verbose_name=_("BPMS user login"), unique=True)
    password = models.CharField(max_length=50,  verbose_name=_("BPMS user password"))
    phone = models.CharField(max_length=50,  verbose_name=_("BPMS user phone"), blank=True, null=True)
    web_user = models.OneToOneField(User, blank=True, null=True, on_delete=models.SET_NULL,
                                    verbose_name=_("Web user of BPMS account"))

    def __str__(self):
        return self.login

    class Meta:
        verbose_name = _('BPMS User')
        verbose_name_plural = _('BPMS Users')
        ordering = ['login']


class TaskFile(models.Model):
    file = models.FileField(upload_to='comments_files/%f%d%m%y/')
    key = models.CharField(max_length=200)
    purpose = models.CharField(max_length=200)


from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=TaskFile)
def mymodel_delete(sender, instance, **kwargs):
    file_folder = os.path.join(settings.MEDIA_ROOT, ntpath.split(instance.file.name)[0])
    instance.file.delete(False)
    os.rmdir(file_folder)

activeBPM/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from activeBPM.activiti_api import ActivityREST
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from activeBPM.models import TaskFile
from django.template import TemplateDoesNotExist
from activeBPM import process_forms_default
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import os
import ntpath
import json
import time
template_folder = 'activeBPM'
proc_dashbord_template = os.path.join(template_folder, 'proc_dashbord.html')
all_proc_template = os.path.join(template_folder, 'all_proc.html')
proc_control_template = os.path.join(template_folder, 'proc_control.html')
proc_status_template = os.path.join(template_folder, 'proc_base.html')
task_template = os.path.join(template_folder, 'task.html')
proc_init_template = os.path.join(template_folder, 'proc_base.html')
category = 'molds_development'
from activeBPM import molds_documentation_forms as forms_module
folders_paths = {'molds_documentation': os.path.join(settings.MEDIA_ROOT, 'Dropbox/molds_documentation/')}


#TODO profile
#TODO add a web account existance check
#TODO add a user group check if will be other modules than molds
#TODO add right permissions to admin and other groups
#TODO add a process sort by last state change
#TODO localization
#from silk.profiling.profiler import silk_profile
#@silk_profile(name='View main process list')
@login_required()
def proc_dashboard_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    active_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='active')

    #TODO fix: not latest two from every latest def, but simply latest two
    finished_proc_table = rest_client.get_proc_instncs_info_by_category(category,
                                                                                       def_state='active',
                                                                                       instnc_state='finished',
                                                                                       quantity_per_def=2,
                                                                                       latest_def=True)

    admin_userids = rest_client.get_group_userids_by_group_name('admin')
    if request.user.bpmsuser.login in admin_userids:
        assignee_task_table = rest_client.get_tasks_info()
    else:
        assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login) + \
            rest_client.get_tasks_info(candidate_user=request.user.bpmsuser.login)

    if request.user.bpmsuser.login in admin_userids:
        available_proc_table = rest_client.get_proc_defs_info_by_category(category=category, def_state='active',
                                                                     latest_def=True)
    else:
        available_proc_table = rest_client.get_proc_defs_info_by_category(category=category, def_state='active',
                                                                     latest_def=True,
                                                                     startable_by_user=request.user.bpmsuser.login)
    tmpl_dict = {'active_proc_table': active_proc_table,
                 'finished_proc_table': finished_proc_table,
                 'assignee_task_table': assignee_task_table,
                 'available_proc_table': available_proc_table}
    return render(request, proc_dashbord_template, tmpl_dict)


@login_required()
def all_proc_view(request):
    #from activeBPM.tasks import new_task_sms
    #new_task_sms()
    #return HttpResponse('ok')
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)

    active_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='active')
    suspended_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='suspended')
    finished_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='finished')
    tmpl_dict = {
        'active_proc_table': active_proc_table,
        'finished_proc_table': finished_proc_table,
        'suspended_proc_table': suspended_proc_table
    }
    return render(request, all_proc_template, tmpl_dict)


@login_required()
def proc_status_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_instnc_id = request.GET['instnc_id']
    proc = rest_client.get_proc_instnc_info(proc_instnc_id)
    tmpl_dict = {'proc': proc}
    return render(request, proc_status_template, tmpl_dict)


#TODO check if task is a task of right user and process is active
#TODO simplify
@login_required()
def task_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_instnc_id = request.GET['instnc_id']
    task_id = request.GET['task_id']
    proc = rest_client.get_proc_instnc_info(proc_instnc_id)
    task = rest_client.get_task_info(task_id)
    try:
        task_form_class = getattr(forms_module, '%s__%s' % (proc['def_key'], task['def_key']))
    except AttributeError:
        try:
            task_form_class = getattr(forms_module, 'TaskDefault')
        except AttributeError:
            task_form_class = getattr(process_forms_default, 'TaskDefault')
    if request.method == 'POST':
        admin_userids = rest_client.get_group_userids_by_group_name('admin')
        task_form = task_form_class(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data
            rest_client.set_proc_vars(proc_instnc_id, data)
            rest_client.complete_task(task_id)
            task_form.after_complete()
            if request.user.bpmsuser.login in admin_userids:
                assignee_task_table = rest_client.get_tasks_info()
            else:
                assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login)

            next_tasks = [task for task in assignee_task_table if task['proc_instnc_id'] == proc_instnc_id]
            if len(next_tasks) == 1:
                next_task_id = next_tasks[0]['id']
                return HttpResponseRedirect(reverse("activeBPM:process-task")
                                     + '?instnc_id=%s&task_id=%s' % (proc_instnc_id, next_task_id))
            else:
                return HttpResponseRedirect(reverse("activeBPM:process-status") + '?instnc_id=%s' % proc_instnc_id)
        else:
            if request.user.bpmsuser.login in admin_userids:
                errors = task_form.errors
                return HttpResponse(str(errors))
            else:
                pass #error for users
    else:
        task_form = task_form_class()
    proc_template_folder = os.path.join(template_folder, 'proc_templates', proc['def_key'], '')
    proc_task_default_template = os.path.join(proc_template_folder, 'task_default.html')
    proc_task_main_default_template = 'activeBPM/proc_templates/default_process/task_default.html'
    task_tmpl = os.path.join(proc_template_folder, '%s__%s.html' % (proc['def_key'], task['def_key']))
    tmpl_dict = {'proc': proc, 'task': task, 'task_form': task_form}
    try:
        return render(request, task_tmpl, tmpl_dict)
    except TemplateDoesNotExist:
        try:
            return render(request, proc_task_default_template, tmpl_dict)
        except TemplateDoesNotExist:
            return render(request, proc_task_main_default_template, tmpl_dict)


#TODO init files loading works incorrect. Need right init behavior in process history and in file uploading
#TODO simplify
#upload with nowtime and then update key to process instance id - bed idea
@login_required()
def proc_init_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_def_id = request.GET['def_id']
    proc = rest_client.get_proc_def_info(proc_def_id)
    init_task_id = 'init_%s_%s' % (request.user.bpmsuser.login, proc['def_key'])
    try:
        task_form_class = getattr(forms_module, '%s__%s' % (proc['def_key'], 'init'))
    except AttributeError:
        try:
            task_form_class = getattr(forms_module, 'ProcessInitDefault')
        except AttributeError:
            task_form_class = getattr(process_forms_default, 'ProcessInitDefault')
    if request.method == 'POST':
        task_form = task_form_class(request.POST)
        admin_userids = rest_client.get_group_userids_by_group_name('admin')
        if task_form.is_valid():
            data = task_form.cleaned_data
            #data['worker'] = '124bit'
            proc_instnc = rest_client.start_proc(proc_def_id, data)
            proc_instnc_id = proc_instnc['id']
            task_files = TaskFile.objects.filter(key='_' + init_task_id, purpose='comment')
            for task_file in task_files:
                task_file.key = proc_instnc_id + '_init'
                task_file.save()
            task_form.after_complete()
            if request.user.bpmsuser.login in admin_userids:
                assignee_task_table = rest_client.get_tasks_info()
            else:
                assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login)
            next_tasks = [task for task in assignee_task_table if task['proc_instnc_id'] == proc_instnc_id]
            if len(next_tasks) == 1:
                next_task_id = next_tasks[0]['id']

activeBPM/templates/activeBPM/proc_base.html
{% extends "activeBPM/base.html" %}
{%  load activeBPM_tags %}

{% block middle %}
    {% block task_panel %}
    {% endblock %}

    {% block process_panel %}
        <div class='row'>
            <div class='col-md-12'>
                <div class="panel panel-default" style="min-width: 420px;">
                    <div class="panel-heading">
                        {% block process_heading %}
                            <h4>Процесс:<i> {{ proc.name }} {{ proc.vars.proc_individ_descr }}</i></h4>
                            <p> Статус: <i>{% if proc.state == 'active' %}Активен{% elif proc.state == 'suspended' %}приостановлен{% elif proc.state == 'finished' %}Окончен{% endif %}</i></p>
                            {% if proc.descr %}<p>Описание: <i>{{ proc.descr }} </i></p>{% endif %}
                        {% endblock %}
                    </div>
                    {% block process_diagram %}
                        <div class='row'>
                            <div class='col-md-12'>
                                <div id="bp_canvas"></div>
                            </div>
                        </div>
                        <script>
                            (function(BpmnViewer, $) {

                                var bpmnViewer = new BpmnViewer({
                                    container: '#bp_canvas',
                                    width: '100%',
                                    height: '500px'
                                });

                                function importXML(xml) {

                                    bpmnViewer.importXML(decodeURIComponent(escape(xml)), function(err) {

                                    if (err) {
                                        return console.error('could not import BPMN 2.0 diagram', err);
                                    }

                                    var canvas = bpmnViewer.get('canvas')
                                    var overlays = bpmnViewer.get('overlays');

                                    canvas.zoom('fit-viewport');
                                    $(document).ready( function () {
                                        if (typeof show_task == 'function') {
                                            show_task();
                                        };
                                    })
                                    });
                                }

                                $.get('{% url "activeBPM:process-xml" %}?def_id={{ proc.def_id }}', importXML);

                            })(window.BpmnJS, window.jQuery);

                            $('.bjs-powered-by').remove()
                        </script>
                        <script>
                            var show_task = function  () {
                                {% if proc.state == 'finished' %}

                                    $('g[data-element-id="endevent"]').find('.djs-outline').attr('stroke', 'Maroon').attr('stroke-dasharray', '5,5');
                                    $('g[data-element-id="endevent"]').find('.djs-visual circle').attr('fill', '#FFFF00')
                                {% elif not proc.state %}
                                    $('g[data-element-id="startevent"]').find('.djs-outline').attr('stroke', 'Maroon').attr('stroke-dasharray', '5,5');
                                    $('g[data-element-id="startevent"]').find('.djs-visual circle').attr('fill', '#FFFF00')
                                {% else %}
                                    active_tasks = [{% for task in proc.active_tasks %}'{{ task.def_key }}', {% endfor %}];
                                    for(var i = 0; i < active_tasks.length; i++) {
                                        $('g[data-element-id="' + active_tasks[i] + '"]').find('.djs-visual rect').attr('fill', '#FFFF00').attr('fill-opacity','0.5');
                                    }
                                {% endif %}
                                {%  if task %}
                                    $('g[data-element-id="' + '{{ task.def_key }}' + '"]').find('.djs-outline').attr('stroke', 'Maroon').attr('stroke-dasharray', '5,5');
                                {%  endif %}
                            }
                        </script>

                    {% endblock %}
                </div>
            </div>
        </div>
    {% endblock %}


    {% block active_tasks %}
        {% if proc.active_tasks %}
            <div class="row">
                <div class='col-md-12'>
                    <div class="panel panel-default">
                        <div class="panel-heading">Активные задачи</div>
                        <table class="table">
                            <tr>
                                <th>Задача</th>
                                <th>Исполнитель</th>
                                <th>Получено</th>
                                <th>Взято в работу</th>
                            </tr>
                            {% for task in proc.active_tasks %}
                             <tr>
                                <td>{{ task.name }}</td>
                                <td>
                                    {% if task.assignee %}
                                        {{ task.assignee_profile.firstName.0 }}. {{ task.assignee_profile.lastName }}
                                    {% else %}
                                Назначено {% for group in task.groups %}
                                    {{ group.name|lower }}{% if not forloop.last %}, {% endif %}{%  endfor %}, в роботу не принято
                            {%  endif %}
                                </td>
                                <td>{{ task.start_time|format_date:"%d %b %H:%M"}}</td>
                                <td>
                                    {% for task in proc.active_tasks %}
                                        {% if task.start_time == task.assign_time %}
                                            Назначено автоматически
                                        {% else %}
                                            {{ task.assign_time|format_date:"%d %b %H:%M" }}
                                        {% endif %}
                                        {% if not forloop.last %}
                                            <br>
                                        {% endif %}
                                    {% endfor %}
                                </td>
                             </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock %}

    {% block finished_tasks %}
        {% if proc.finished_tasks %}
             <div class="row">
                    <div class='col-md-12'>
                        <div class="panel panel-default">
                            <div class="panel-heading">Законченные задачи</div>
                            <table class="table">
                                <tr>
                                    <th>Задача</th>
                                    <th>Исполнитель</th>
                                    <th>Длительность</th>
                                    <th>Закончено</th>
                                    <th>Комментарий</th>
                                    <th></th>
                                </tr>
                                {% for task in proc.finished_tasks %}
                                    <tr>
                                        <td>{{ task.name }}</td>
                                        <td>{{ task.assignee_profile.firstName.0 }}. {{ task.assignee_profile.lastName }}</td>
                                        <td>{{ task.full_time|format_delta }}</td>
                                        <td>{{ task.end_time|format_date:"%H:%M %d %b %Y" }}</td>
                                        <td>{{ task.vars.task_comment }}</td>
                                        <td>
                                            {% for file in task.comment_files %}
                                                <p>
                                                    <a href="{% url "activeBPM:file-control" %}?file_pk={{ file.file_pk }}">
                                                        <span class="glyphicon glyphicon-file"></span>{{ file.name }}
                                                    </a>
                                                </p>
                                            {%  endfor %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
             </div>
        {% endif %}
    {%  endblock %}

{% endblock %}

activeBPM/templates/activeBPM/proc_dashbord.html
{% extends "activeBPM/base.html" %}
{% load activeBPM_tags %}

{% block middle %}
<div class="row">
    <div class='col-md-12'>
        <div class="panel panel-default">
            <div class="panel-heading">Ваши задачи</div>
            <table class="table">
                <tr>
                    <th>Задача</th>
                    <th>Процесс</th>
                    <th>Получено</th>
                    <th></th>
                </tr>
                {% for task in assignee_task_table %}
                    <tr>
                        <td>
                            <a href="{% url 'activeBPM:process-task' %}?instnc_id={{ task.proc_instnc_id }}&task_id={{ task.id }}">{{ task.name }}</a>
                        </td>
                        <td>
                            {{ task.proc_name }} {{ task.vars.proc_individ_descr }}
                        </td>
                        <td>
                            {{  task.start_time|format_date:"%d %b %H:%M" }}
                        </td>
                        <td>
                            {% if task.assignee %}
                                <form action="{% url 'activeBPM:task-control' %}" method="post" id='unassign_{{ task.id }}' style="display:none;">
                                    {% csrf_token %}
                                    <input type="hidden" name="task_id" value="{{ task.id }}"/>
                                    <input type="hidden" name="action" value="unassign"/>
                                </form>
                                <div class="btn-group btn-group-xs" style="width: 170px;">
                                    <button class="btn btn-success" type="button" onclick="window.location = '{% url 'activeBPM:process-task' %}?instnc_id={{ task.proc_instnc_id }}&task_id={{ task.id }}';">Продолжить</button>
                                    <button class="btn btn-danger" type="button" onclick="$('#unassign_{{ task.id }}').submit();">Отказаться</button>
                                </div>
                            {%  else %}
                                <form action="{% url 'activeBPM:task-control' %}" method="post" id='assign_{{ task.id }}' style="display:none;">
                                    {% csrf_token %}
                                    <input type="hidden" name="instnc_id" value="{{ task.proc_instnc_id }}"/>
                                    <input type="hidden" name="task_id" value="{{ task.id }}"/>
                                    <input type="hidden" name="action" value="assign"/>
                                </form>
                                <div class="btn-group btn-group-sm">
                                    <button class="btn btn-success" type="button" onclick="$('#assign_{{ task.id }}').submit();">начать</button>
                                </div>
                            {%  endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <div class="panel panel-default">
            <div class="panel-heading">Начать процесс</div>
            <div class="list-group">
                <div style="max-width: 600px;">
                    {% for proc in available_proc_table %}

                          <span class="list-group-item">
                            <a href="{% url 'activeBPM:process-init' %}?def_id={{ proc.def_id }}" ><button class="btn  btn-success btn-sm pull-right"> начать </button></a>
                            <h5 class="list-group-item-heading">{{ proc.name }}</h5>
                            <p class="list-group-item-text"><small>{{ proc.descr }}</small></p>
                          </span>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
    <hr>

<div class="row">
    <div class='col-md-12'>
        <div class="panel panel-default">
            <div class="panel-heading">Активные процессы</div>
            <table class="table">
                <tr>
                    <th>Процесс</th>
                    <th>Задание</th>
                    <th>Задание получено</th>
                    <th>Задание взято в работу</th>
                </tr>
                {% for proc in active_proc_table %}
                    <tr>
                        <td>
                            <a href="{% url 'activeBPM:process-status' %}?instnc_id={{ proc.instnc_id }}">{{ proc.name }} {{ proc.vars.proc_individ_descr }}</a>
                        </td>

                        <td>
                            {% for task in proc.active_tasks %}
                                {{ task.name }}
                                {% if task.assignee %}
                                    (взято {{ task.assignee_profile.firstName.0 }}. {{ task.assignee_profile.lastName }})
                                {% else %}
                                    (назначено {% for group in task.groups %}
                                        {{ group.name|lower }}{% if not forloop.last %}, {% endif %}{%  endfor %})
                                {%  endif %}
                                {% if not forloop.last %}
                                    <br>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for task in proc.active_tasks %}
                                {{ task.start_time|format_date:"%d %b %H:%M" }}
                                {% if not forloop.last %}
                                    <br>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for task in proc.active_tasks %}
                                {% if task.start_time == task.assign_time %}
                                    Назначено автоматически
                                {% else %}
                                    {{ task.assign_time|format_date:"%d %b %H:%M" }}
                                {% endif %}
                                {% if not forloop.last %}
                                    <br>
                                {% endif %}
                            {% endfor %}
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>


    <div class='col-md-12'>
        <div class="panel panel-default">
            <div class="panel-heading">Последние законченные процессы</div>
            <table class="table">
                <tr>
                    <th>Процесс</th>
                    <th>Длительность</th>
                    <th>Закончен</th>
                </tr>
                {% for proc in finished_proc_table %}
                    {%  if forloop.counter <= 10 %}
                        <tr>
                            <td>
                                <a href="{% url 'activeBPM:process-status' %}?instnc_id={{ proc.instnc_id }}">{{ proc.name }} {{ proc.vars.proc_individ_descr }}</a>
                            </td>

                            <td>
                                {{ proc.full_time|format_delta }}
                            </td>

                            <td>
                                {{ proc.end_time|format_date:"%d %b %Y" }}
                            </td>


                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

activeBPM/templates/activeBPM/proc_init.html
{% extends "activeBPM/proc_task.html" %}



{% block process_heading %}
    <h2> Запуск процесса: {{ proc.name }}</h2>
{% endblock %}

{% block task_heading %}
    <h3> Заполните поля</h3>
{% endblock %}