activeBPM/urls.py
__author__ = 'torn'

from django.conf.urls import patterns, include, url
from activeBPM import views
from django.views.generic.base import TemplateView

#TODO 404 page
moldslist_patterns = patterns('',
    url(r'^zip-folder$', views.zip_folder_task_file, name='zip-folder-task-file'),

    url(r'^process-status$', views.proc_status_view, name='process-status'),
    url(r'^process-init$', views.proc_init_view, name='process-init'),
    url(r'^process-task$', views.task_view, name='process-task'),
    url(r'^all-processes$', views.all_proc_view, name='all-processes'),
    url(r'^process-control$', views.proc_control_view, name='process-control'),
    url(r'^task-control$', views.task_control, name='task-control'),
    url(r'^file-control$', views.file_control, name='file-control'),
    url(r'^var-control$', views.var_control, name='variable-control'),
    url(r'^process-xml$', views.proc_xml, name='process-xml'),
    url(r'^doc-view$', TemplateView.as_view(template_name='activeBPM/doc_view.html'),
        name='documentation-view'),
    url(r'^$', views.proc_dashboard_view, name='process-dashboard'),
)

urlpatterns = patterns('',
    url(r'^', include(moldslist_patterns, namespace='activeBPM')),
)

devhim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth.decorators import login_required

handler404 = 'site_utils.handler404'
handler500 = 'site_utils.handler500'

admin.site.site_header = 'УкрХимПласт - Разработка форм'
admin.site_title = 'УкрХимПласт - Разработка форм'
admin.index_title = 'УкрХимПласт - Разработка форм'

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)

urlpatterns = patterns('', url(r'^admin/', include(admin.site.urls)))


if hasattr(settings, 'ENABLE_SILK') and settings.ENABLE_SILK:
    urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('', url(r'^', include('activeBPM.urls'), name='dev-home'))

activeBPM/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import ntpath
import os
from django.conf import settings

#TODO Add a long descriptions, account existence test (all other things is available through BPMS admin)
class BPMSUser(models.Model):
    login = models.CharField(max_length=50,  verbose_name=_("BPMS user login"), unique=True)
    password = models.CharField(max_length=50,  verbose_name=_("BPMS user password"))
    phone = models.CharField(max_length=50,  verbose_name=_("BPMS user phone"), blank=True, null=True)
    web_user = models.OneToOneField(User, blank=True, null=True, on_delete=models.SET_NULL,
                                    verbose_name=_("Web user of BPMS account"))

    def __str__(self):
        return self.login

    class Meta:
        verbose_name = _('BPMS User')
        verbose_name_plural = _('BPMS Users')
        ordering = ['login']


class TaskFile(models.Model):
    file = models.FileField(upload_to='comments_files/%f%d%m%y/')
    key = models.CharField(max_length=200)
    purpose = models.CharField(max_length=200)


from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=TaskFile)
def mymodel_delete(sender, instance, **kwargs):
    file_folder = os.path.join(settings.MEDIA_ROOT, ntpath.split(instance.file.name)[0])
    instance.file.delete(False)
    os.rmdir(file_folder)

activeBPM/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from activeBPM.activiti_api import ActivityREST
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from activeBPM.models import TaskFile
from django.template import TemplateDoesNotExist
from activeBPM import process_forms_default
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import os
import ntpath
import json
import time
template_folder = 'activeBPM'
proc_dashbord_template = os.path.join(template_folder, 'proc_dashbord.html')
all_proc_template = os.path.join(template_folder, 'all_proc.html')
proc_control_template = os.path.join(template_folder, 'proc_control.html')
proc_status_template = os.path.join(template_folder, 'proc_base.html')
task_template = os.path.join(template_folder, 'task.html')
proc_init_template = os.path.join(template_folder, 'proc_base.html')
category = 'molds_development'
from activeBPM import molds_documentation_forms as forms_module
folders_paths = {'molds_documentation': os.path.join(settings.MEDIA_ROOT, 'Dropbox/molds_documentation/')}


#TODO profile
#TODO add a web account existance check
#TODO add a user group check if will be other modules than molds
#TODO add right permissions to admin and other groups
#TODO add a process sort by last state change
#TODO localization
#from silk.profiling.profiler import silk_profile
#@silk_profile(name='View main process list')
@login_required()
def proc_dashboard_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    active_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='active')

    #TODO fix: not latest two from every latest def, but simply latest two
    finished_proc_table = rest_client.get_proc_instncs_info_by_category(category,
                                                                                       def_state='active',
                                                                                       instnc_state='finished',
                                                                                       quantity_per_def=2,
                                                                                       latest_def=True)

    admin_userids = rest_client.get_group_userids_by_group_name('admin')
    if request.user.bpmsuser.login in admin_userids:
        assignee_task_table = rest_client.get_tasks_info()
    else:
        assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login) + \
            rest_client.get_tasks_info(candidate_user=request.user.bpmsuser.login)

    if request.user.bpmsuser.login in admin_userids:
        available_proc_table = rest_client.get_proc_defs_info_by_category(category=category, def_state='active',
                                                                     latest_def=True)
    else:
        available_proc_table = rest_client.get_proc_defs_info_by_category(category=category, def_state='active',
                                                                     latest_def=True,
                                                                     startable_by_user=request.user.bpmsuser.login)
    tmpl_dict = {'active_proc_table': active_proc_table,
                 'finished_proc_table': finished_proc_table,
                 'assignee_task_table': assignee_task_table,
                 'available_proc_table': available_proc_table}
    return render(request, proc_dashbord_template, tmpl_dict)


@login_required()
def all_proc_view(request):
    #from activeBPM.tasks import new_task_sms
    #new_task_sms()
    #return HttpResponse('ok')
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)

    active_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='active')
    suspended_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='suspended')
    finished_proc_table = rest_client.get_proc_instncs_info_by_category(category, def_state='active',
                                                                            instnc_state='finished')
    tmpl_dict = {
        'active_proc_table': active_proc_table,
        'finished_proc_table': finished_proc_table,
        'suspended_proc_table': suspended_proc_table
    }
    return render(request, all_proc_template, tmpl_dict)


@login_required()
def proc_status_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_instnc_id = request.GET['instnc_id']
    proc = rest_client.get_proc_instnc_info(proc_instnc_id)
    tmpl_dict = {'proc': proc}
    return render(request, proc_status_template, tmpl_dict)


#TODO check if task is a task of right user and process is active
#TODO simplify
@login_required()
def task_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_instnc_id = request.GET['instnc_id']
    task_id = request.GET['task_id']
    proc = rest_client.get_proc_instnc_info(proc_instnc_id)
    task = rest_client.get_task_info(task_id)
    try:
        task_form_class = getattr(forms_module, '%s__%s' % (proc['def_key'], task['def_key']))
    except AttributeError:
        try:
            task_form_class = getattr(forms_module, 'TaskDefault')
        except AttributeError:
            task_form_class = getattr(process_forms_default, 'TaskDefault')
    if request.method == 'POST':
        admin_userids = rest_client.get_group_userids_by_group_name('admin')
        task_form = task_form_class(request.POST)
        if task_form.is_valid():
            data = task_form.cleaned_data
            rest_client.set_proc_vars(proc_instnc_id, data)
            rest_client.complete_task(task_id)
            task_form.after_complete()
            if request.user.bpmsuser.login in admin_userids:
                assignee_task_table = rest_client.get_tasks_info()
            else:
                assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login)

            next_tasks = [task for task in assignee_task_table if task['proc_instnc_id'] == proc_instnc_id]
            if len(next_tasks) == 1:
                next_task_id = next_tasks[0]['id']
                return HttpResponseRedirect(reverse("activeBPM:process-task")
                                     + '?instnc_id=%s&task_id=%s' % (proc_instnc_id, next_task_id))
            else:
                return HttpResponseRedirect(reverse("activeBPM:process-status") + '?instnc_id=%s' % proc_instnc_id)
        else:
            if request.user.bpmsuser.login in admin_userids:
                errors = task_form.errors
                return HttpResponse(str(errors))
            else:
                pass #error for users
    else:
        task_form = task_form_class()
    proc_template_folder = os.path.join(template_folder, 'proc_templates', proc['def_key'], '')
    proc_task_default_template = os.path.join(proc_template_folder, 'task_default.html')
    proc_task_main_default_template = 'activeBPM/proc_templates/default_process/task_default.html'
    task_tmpl = os.path.join(proc_template_folder, '%s__%s.html' % (proc['def_key'], task['def_key']))
    tmpl_dict = {'proc': proc, 'task': task, 'task_form': task_form}
    try:
        return render(request, task_tmpl, tmpl_dict)
    except TemplateDoesNotExist:
        try:
            return render(request, proc_task_default_template, tmpl_dict)
        except TemplateDoesNotExist:
            return render(request, proc_task_main_default_template, tmpl_dict)


#TODO init files loading works incorrect. Need right init behavior in process history and in file uploading
#TODO simplify
#upload with nowtime and then update key to process instance id - bed idea
@login_required()
def proc_init_view(request):
    rest_client = ActivityREST(request.user.bpmsuser.login, request.user.bpmsuser.password)
    proc_def_id = request.GET['def_id']
    proc = rest_client.get_proc_def_info(proc_def_id)
    init_task_id = 'init_%s_%s' % (request.user.bpmsuser.login, proc['def_key'])
    try:
        task_form_class = getattr(forms_module, '%s__%s' % (proc['def_key'], 'init'))
    except AttributeError:
        try:
            task_form_class = getattr(forms_module, 'ProcessInitDefault')
        except AttributeError:
            task_form_class = getattr(process_forms_default, 'ProcessInitDefault')
    if request.method == 'POST':
        task_form = task_form_class(request.POST)
        admin_userids = rest_client.get_group_userids_by_group_name('admin')
        if task_form.is_valid():
            data = task_form.cleaned_data
            #data['worker'] = '124bit'
            proc_instnc = rest_client.start_proc(proc_def_id, data)
            proc_instnc_id = proc_instnc['id']
            task_files = TaskFile.objects.filter(key='_' + init_task_id, purpose='comment')
            for task_file in task_files:
                task_file.key = proc_instnc_id + '_init'
                task_file.save()
            task_form.after_complete()
            if request.user.bpmsuser.login in admin_userids:
                assignee_task_table = rest_client.get_tasks_info()
            else:
                assignee_task_table = rest_client.get_tasks_info(assignee=request.user.bpmsuser.login)
            next_tasks = [task for task in assignee_task_table if task['proc_instnc_id'] == proc_instnc_id]
            if len(next_tasks) == 1:
                next_task_id = next_tasks[0]['id']

activeBPM/templates/activeBPM/proc_templates/molds_documentation/common_filenames.html
                        <select class='form-control' id='filename_select'>
                            <optgroup value='0. Техническое задание' label='0. Техническое задание'>
                                <option value='ТЗ'>ТЗ</option>
                            </optgroup>
                            <optgroup value='1. Изделие' label='1. Изделие'>
                                <option value='Модель изделия'>Модель изделия</option>
                                <option value='Чертеж изделия'>Чертеж изделия</option>
                            </optgroup>
                            <optgroup value='2. Форма' label='2. Форма'>
                                <option value='Модель формы'>Модель формы</option>
                                <option value='Модель формы с обвязкой'>Модель формы с обвязкой</option>
                                <option value='Чертеж формы'>Чертеж формы</option>
                                <option value='Чертеж формы с обвязкой'>Чертеж формы с обвязкой</option>
                                <option value='Чертеж формы позиции'>Чертеж формы позиции</option>
                                <option value='Деталировка'>Деталировка *</option>
                                <option value='Деталировка - фланец'>Деталировка - фланец</option>
                            </optgroup>
                            <optgroup value='3. Раскрой' label='3. Раскрой'>
                                <option value='Раскрой'>Раскрой *</option>
                                <option value='Раскрой - фланец'>Раскрой - фланец</option>
                                <option value='Гравировка'>Гравировка</option>
                                <option value='Ручной раскрой'>Ручной раскрой</option>
                            </optgroup>
                            <optgroup value='4. Проектная документация (pdf)' label='4. Проектная документация (pdf)'>
                                <option value='Титульная страница'>Титульная страница</option>
                                <option value='Чертеж изделия'>Чертеж изделия</option>
                                <option value='Чертеж формы'>Чертеж формы</option>
                                <option value='Чертеж формы с обвязкой'>Чертеж формы с обвязкой</option>
                                <option value='Чертеж формы позиции'>Чертеж формы позиции</option>
                                <option value='Деталировка'>Деталировка *</option>
                                <option value='Деталировка - фланец'>Деталировка - фланец</option>
                                <option value='Ручной раскрой'>Ручной раскрой</option>
                                <option value='Гравировка'>Гравировка</option>
                            </optgroup>
                            <optgroup id="other_optgroup" value='Другое' label='Другое'>
                                <option value='Другой файл'>Другой файл</option>
                            </optgroup>
                        </select>

activeBPM/templates/activeBPM/proc_templates/molds_documentation/molds_documentation__documentation_audit.html
{% extends 'activeBPM/proc_templates/default_process/task_default.html' %}
{% load activeBPM_tags %}

{% block main_form_fields %}
    <div class='row'>
        <div class="col-md-12"><label>Файлы формы:</label></div>
        <div class="col-md-12">
            <div style="margin-left: 20px;" id="mold_files_list"></div>
        </div>
        <div class="col-md-12" style="margin-top: 10px;">
            <div style="width: 200px;">
                <div id="dropbox_button" style="display: none;">
                    <div style="width: 180px; opacity:0.5;">
                        <a class="btn btn-block btn-social btn-dropbox btn-xs">
                            <i class="fa fa-dropbox"></i> Посмотреть на Dropbox
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='row' style="margin-top: 20px;">
        <div class="col-md-12">
            <label>Не загруженные файлы:</label>
            <ul class="list-group" id="not_uploaded_files" style="margin-left: 20px; list-style-type: none;">
            </ul>
        </div>
        <div class="col-md-12">
            <label>Не заполненные поля спецификации:</label>
            <ul class="list-group" id="not_filled_fields" style="margin-left: 20px; list-style-type: none;">
            </ul>
        </div>
    </div>
    <div style="display: none;">
        {% include 'activeBPM/proc_templates/molds_documentation/common_filenames.html' %}
        {% include 'activeBPM/proc_templates/molds_documentation/specification_fields.html' %}
    </div>
    <hr>



    <style>
        @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);

        .btn-dropbox{color:#fff;background-color:#1087dd;border-color:rgba(0,0,0,0.2)}.btn-dropbox:hover,.btn-dropbox:focus,.btn-dropbox:active,.btn-dropbox.active,.open .dropdown-toggle.btn-dropbox{color:#fff;background-color:#0d70b7;border-color:rgba(0,0,0,0.2)}
    .btn-dropbox:active,.btn-dropbox.active,.open .dropdown-toggle.btn-dropbox{background-image:none}
    .btn-dropbox.disabled,.btn-dropbox[disabled],fieldset[disabled] .btn-dropbox,.btn-dropbox.disabled:hover,.btn-dropbox[disabled]:hover,fieldset[disabled] .btn-dropbox:hover,.btn-dropbox.disabled:focus,.btn-dropbox[disabled]:focus,fieldset[disabled] .btn-dropbox:focus,.btn-dropbox.disabled:active,.btn-dropbox[disabled]:active,fieldset[disabled] .btn-dropbox:active,.btn-dropbox.disabled.active,.btn-dropbox[disabled].active,fieldset[disabled] .btn-dropbox.active{background-color:#1087dd;border-color:rgba(0,0,0,0.2)}
        .btn-social{position:relative;padding-left:44px;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.btn-social :first-child{position:absolute;left:0;top:0;bottom:0;width:32px;line-height:34px;font-size:1.6em;text-align:center;border-right:1px solid rgba(0,0,0,0.2)}
        .btn-social.btn-sm{padding-left:38px}.btn-social.btn-sm :first-child{line-height:28px;width:28px;font-size:1.4em}
        .btn-social.btn-xs{padding-left:30px}.btn-social.btn-xs :first-child{line-height:20px;width:20px;font-size:1.2em}
    </style>

    <script>
        var mold_folder = "{{ proc.vars.mold_folder }}";
        var mold_files;

        function read_spec(){

            var string_data = $.ajax({
                    url: "{{ MEDIA_URL }}/Dropbox/molds_documentation/" + mold_folder +'/спецификация.txt',
                    async: false
                 }).responseText;
            string_data = string_data.substring(string_data.indexOf("["));
            string_data = string_data.substring(1);  // one more for '['
            string_data = string_data.substring(0, string_data.length - 1);
            var split_text = string_data.split('\n[');
            for (var i = 0; i < split_text.length; i++) {
                var field_props = split_text[i].split(']\n');
                var field_id = $('label').filter(function() {
                    return $(this).text() == field_props[0];
                }).attr('for');

                $('#' + field_id).val(field_props[1]);
            }

            var fields = $('#fields_div input').add('#fields_div textarea');
            for (var i = 0; i < fields.length; i++){
                 var field = $(fields[i]);
                 var field_val = field.val();

                 if (field_val.replace(/\s/g, "").replace('-', "") == ''){
                     $('#not_filled_fields').append('<li>'  + (i + 1) + '. '+ $('label[for=' + field.attr('id') +']').text() + '</li>');
                 }
            }
        }

        function color_select() {
            $("#filename_select option").css('color','#555').attr('data-uploaded','false');
            $("#filename_select").css('color','#555');
            $("#filename_select optgroup").css('color','#555');
            for (var i = 0; i < mold_files.length; i++)
            {
                var mold_filename = mold_files[i]['name'].split('.').slice(0, -1).join('');

                $('optgroup[value="'+mold_files[i]['folder_path']+'"]').find("option[value='" + mold_filename +"']").css('color','green').attr('data-uploaded','true');


                if ($('optgroup[value="'+mold_files[i]['folder_path']+'"]').find("option[value='" + mold_filename +"']:selected").length>0) {
                    $("#filename_select").css('color','green');
                }
            }
        }


        function get_mold_files() {
            $.post('{% url "activeBPM:file-control" %}', {folder_path: mold_folder, action: 'get_files_props', csrfmiddlewaretoken: '{{ csrf_token }}', folder_shortcut: 'molds_documentation'}, function (data) {
                        $('#mold_files_list').html('');
                        $('#dropbox_button').css('display', 'none');
                        for (var i = 0; i < data.length; i++)
                        {
                            var href_str = 'href="{{ MEDIA_URL }}' +'Dropbox/molds_documentation/'+ mold_folder + '/' + data[i]['folder_path'] + '/' + data[i]['name'] + '"';
                            var append_str = '<p><a ' + href_str + '><span class="glyphicon glyphicon-file"></span>'+data[i]['folder_path']+ '/'+data[i]['name']+'</a></p>';
                            $('#mold_files_list').append(append_str);
                        }
                        if (data.length>0) $('#dropbox_button').css('display', 'block');
                        else $('#mold_files_list').html('<p>Нет файлов</p>');
                        mold_files = data;
                        color_select();

                        var options = $('#filename_select option');
                        for (var i = 0; i < options.length; i++)
                        {
                           var el = $(options[i]);
                           if (el.attr('data-uploaded') != 'true' && el.parent().attr('value') != 'Другое'){
                               var el_val = el.val()
                               var path =  el.parent().attr('value') + '/' + el_val;
                               $('#not_uploaded_files').append('<li>' + path + '</li>');
                           }
                        }
                    });
        }



        function end_task(){
            $.post('{% url "activeBPM:zip-folder-task-file" %}', {folder_path: mold_folder, csrfmiddlewaretoken: '{{ csrf_token }}', folder_shortcut: 'molds_documentation', task_id: '{{ task.id }}', instnc_id: '{{ proc.instnc_id }}', purpose: 'comment'});
            $('#main_task_form').submit();
        }

        $(document).ready(function(){
            get_mold_files();
            read_spec();

            $('#dropbox_button').click(function(){
                window.open('https://www.dropbox.com/home/molds_documentation/{{ proc.vars.mold_folder }}');
            });

            $('#task_end_button').click(function(e){
                e.preventDefault();
                $('#main_task_form').append('<input type="hidden" name="documentation_valid" value="False" />');
                end_task();
            });

            $('#task_end_button_2').click(function(e){
                e.preventDefault();

                $('#main_task_form').append('<input type="hidden" name="documentation_valid" value="True" />');
                end_task();
            });

        });
    </script>
{% endblock %}

{% block submit_button %}
    <div class="row" style="margin-top:20px;">
        <div class='col-md-12'>
            <button style="width: 200px;" id="task_end_button" class="btn btn-warning" type="submit">Документация не валидна</button>
            <button style="width: 200px; margin-left:20px" id="task_end_button_2" class="btn btn-success" type="submit">Документация валидна</button>
        </div>
    </div>
{% endblock %}

activeBPM/templates/activeBPM/proc_templates/molds_documentation/molds_documentation__folder_choice.html
{% extends 'activeBPM/proc_templates/default_process/task_default.html' %}
{% load activeBPM_tags %}
{% load moldsDev_tags %}

{% block main_form_fields %}
    <div class='row' style="margin-top:20px;">
        <div class="col-md-12"><label>Выберите папку:</label></div>
        <div class="col-md-12">
                <div class="radio" style="width:200px; float:left; margin-left:30px;">
                    <label>
                        <input type="radio" name="folder_state" value="new_folder" id="folder_state_new">
                        Папки еще нет<br> (создать автоматически)
                    </label>
                </div>
                <div class="radio" style="width:120px; float:left; margin-top: 10px;">
                    <label>
                        <input type="radio" name="folder_state" value="old_folder" id="folder_state_old">
                        Папка уже есть
                    </label>
                </div>
        </div>
    </div>

    <div class='row' style="margin-top:10px; display:none;" id="on_folder_state_old">
         <div class="col-md-12">
            <div class="form-group">
                <label for="folder_select" class="control-label">Выберите папку</label>
                <select class="form-control" name='folder_select' id='folder_select' style="width: 400px; margin-left: 20px;">
                    {% get_mold_folders  as mold_folders %}
                    {% for folder in mold_folders %}
                        <option value="{{ folder }}" >{{  folder }}</option>
                    {% endfor %}
                </select>
            </div>
         </div>
    </div>
    <div id="on_folder_state_new">
        <div class='row' style="margin-top:20px;">
            <div class="col-md-12"><label>Номер и название формы:</label></div>
            <div class="col-md-12" style="margin-top:10px;">
                <div class="form-group" style="width: 180px; float: left; ">
                    <div class="input-group">
                        <div class="input-group-addon">№</div>
                        <input type="number" class="form-control" name="mold_number" min="100" max="9999" id="mold_number" placeholder='Номер формы' required>
                     </div>
                </div>
                <div class="form-group" style="margin-left: 20px; width:220px; float: left;">
                        <input type="text" class="form-control" name="mold_name" maxlength="100" id="mold_name" placeholder='Название формы' required>
                </div>
            </div>
            <div class="col-md-12"><p class="help-block" style="margin-top: -10px; font-size: 13px;">* Близкую модификацию указывайте через тире, т.е. G-150-1</p></div>
        </div>



        <div class='row' style="margin-top:20px;">
            <div class="col-md-12"><label>Форма является копией другой формы?</label></div>
            <div class="col-md-12">
                    <div class="radio" style="margin-left:30px; float:left;">
                        <label>
                            <input type="radio" name="check_copy" value="no_copy" id="check_copy_false" checked>
                            Нет
                        </label>
                    </div>
                    <div class="radio" style="margin-left: 30px; float:left; margin-top: 10px;">
                        <label>
                            <input type="radio" name="check_copy" value="copy_exists" id="check_copy_true">
                            Да
                        </label>
                    </div>
            </div>
        </div>

        <div class='row' style="margin-top:10px; display:none;" id="on_check_copy_true">
             <div class="col-md-12">
                <div class="form-group" style="margin-left:50px;">
                    <label for="folder_select" class="control-label">Выберите эту форму</label>
                    <select class="form-control" name='copy_folder_select' id='copy_folder_select' style="min-width: 220px; margin-left: 20px;">
                        {% get_mold_folders with_temp_docs=False as mold_folders %}
                        {% for folder in mold_folders %}
                            <option value="{{ folder }}" >{{ folder }}</option>
                        {% endfor %}
                    </select>
                </div>
             </div>
        </div>
    </div>
    <hr>
    <script>
        $(document).ready(function(){
            $('#folder_state_new').click(function() {
                $('#on_folder_state_new').show();
                $('#on_folder_state_old').hide();
                $("#mold_number").prop('required', true);
                $("#mold_name").prop('required', true);
            });
            $('#folder_state_old').click(function() {
                $('#on_folder_state_old').show();
                $('#on_folder_state_new').hide();
                $("#mold_number").prop('required', false);
                $("#mold_name").prop('required', false);
            });
            $('#folder_state_new').click();


//            $('#folder_select').change(function() {
//                var folder_name = this.value;
//                folder_name = folder_name.split(' (')[0];
//
//                try {
//                    var mold_number = folder_name.split('. ')[0];
//                    var mold_name = folder_name.split('. ')[1];
//
//                    $('#mold_name').val(mold_name);
//                    $('#mold_number').val(mold_number);
//                }
//                catch(e){}
//            });

        });
    </script>
{%  endblock %}



{% block form_attrs %}action="{% url 'activeBPM:process-task' %}?instnc_id={{ task.proc_instnc_id }}&task_id={{ task.id }}" method="post"{% endblock %}